### ISSUE TITLE
Compile doesn't work

### ISSUE THREAD

**Issue by kasperkamperman** [chuank/particle-offline-compiler#3]
Atom 1.5.3. 
I've installed this version of Atom, because I couldn't run this in Particle Dev. 

Pressing compile locally + DFU upload doesn't do anything. Connected to the serial port (that works), and I've started the program from the terminal. I also tried putting the Photon in DFU mode, but then it disappears in DFU serial port list. 

Toggle compile/upload CONSOLE, shows me an HTML console:

<img width="1280" alt="screen shot 2016-02-25 at 20 45 26" src="https://cloud.githubusercontent.com/assets/1760616/13332104/be313742-dc00-11e5-895a-2ca1bacb197b.png">

I was wondering if this project is still maintained?

**Comment by kennethlimcp** [comment]
Can you select a device and compile again? It says not devices selected below.

**Comment by chuank** [comment]
Hi @kasperkamperman,

Do you have a local clone of the `spark-firmware` repository on your machine?

You need to tell the package where you installed it, in the package's preferences window:
![image](https://cloud.githubusercontent.com/assets/1781911/13342380/0a638090-dc95-11e5-8dcc-4f8415e9d856.png)

re: the Developer Console – click on the Console link after toggling the sidebar – what was the error message shown?

Please note that this package is meant for completely _offline_ coding and uploading (i.e. no cloud connection to Particle.io), so you have to manage your own local `spark-firmware` a.k.a. system firmware repo. It also means you have to manage your own code libraries.

At this time, the _compile locally + DFU update_ works; once I get some extra time I'll work on adding OTA updates.

This package is different from the standalone **Particle Dev**, or the **atom/spark-dev** package which still leverages the Particle.io cloud connection to compile and flash firmware.

You might also want to check out https://github.com/spark/particle-dev-local-compiler, which was released a few months back and does something similar. My package is kept simple to allow easy use of custom system firmware.

**Comment by kasperkamperman** [comment]
I'm aware that this package is for offline coding and uploading use. The alternative you mention the partile-dev-local-compiler is a bit to big (install Docker etc.) for its purpose I think. 

I have local compiling already working with the spark-firmware method like described on: https://github.com/spark/firmware/blob/latest/docs/gettingstarted.md

Although I like your solution to do everything from Atom, so I prefer using that. 

First fix: I've changed the compiler path. Maybe you should make that more clear in your readme.

The readme says: 

> Before using it, open up the settings on the package, and enter the Particle Compiler Path – this should point to the location where you downloaded and compiled the particle local compiler (see instructions above).

Maybe you should add that you have to point to the **main** directory of that folder (or use that screenshot you've posted above).  

The console seems to work good now (don't ask me why). I get the following output:

```
[compile] Command: make all -C ~/firmware/main APPDIR=/Users/kamperman/.atom TARGET_DIR=/Users/kamperman/.atom/firmware/photon PLATFORM=photon program-dfu PARTICLE_SERIAL_DEV=/dev/tty.usbmodem1411
particle-offline-compiler.coffee:72 [compile] STDOUT: /Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../modules/photon/user-part all program-dfu

particle-offline-compiler.coffee:73 [compile] STDERR: /bin/sh: arm-none-eabi-gcc: command not found

particle-offline-compiler.coffee:73 [compile] STDERR: /Users/kamperman/firmware/build/arm-tools.mk:42: *** "ARM gcc version 4.8.4 or later required, but found ".  Stop.

particle-offline-compiler.coffee:73 [compile] STDERR: make: *** [modules/photon/user-part] Error 2

particle-offline-compiler.coffee:74 [compile] Exited with 2
```

I started Atom from the terminal. 

It can't find my gcc-arm installation. I stored mine in `usr/local/gcc_arm/gcc-arm-none-eabi-5_2-2015q4/` and added the path to my system. I've actually followed the steps in this
[Sparkfun tutorial](https://learn.sparkfun.com/tutorials/photon-development-guide/all#arm-gcc-and-the-dfu-bootloader-offline).

**Comment by chuank** [comment]
Thanks for the suggestion @kasperkamperman, I'll put in the screenshot to help explain that bit about the **main** folder.

> [compile] Command: make all -C ~/firmware/main APPDIR=/Users/kamperman/.atom TARGET_DIR=/Users/kamperman/.atom/firmware/photon PLATFORM=photon program-dfu PARTICLE_SERIAL_DEV=/dev/tty.usbmodem1411

It looks like you stored `spark-firmware` i.e. compiler path on your home folder? Are you also storing your project code i.e. appdir in your ~/.atom folder? If so, move them to another folder location such as `~/spark-firmware~` and `~/particle_projects` respectively? Or, more likely, perhaps some other toolchain or atom package is affecting the way the package is running. I'd also try nuking the package and perhaps atom, and trying again. I'm not sure if this is the problem with the package but more with your system's environment variables.

Have you also tried running the make command direct from Terminal, and see if you get the same problems? If so, you might have to figure out what happened in your arm-gcc toolchain setup. Like the Sparkfun tutorial hinted, it could be the environment variables on your machine that needs a closer look. [This link covers that too.](https://github.com/spark/firmware/blob/develop/docs/gettingstarted.md#common-errors)

I'm assuming you're on OSX from your log. Try running `which arm-none-eabi-gcc` and see if a symlink was ever created? I went the [homebrew](http://brew.sh/) route to install arm-gcc which handled the symlinks for me without issue.

**Comment by kasperkamperman** [comment]
- The project code is stored in firmware/users/applications
- The Make command works directly from Terminal

I installed arm gcc now with homebrew (I can only find the formula for 4.9) `brew install gcc-arm-none-eabi-49` and that brings me one step further in the progress. Although I get now another error. 

I think the error is related to a missing uuid file? Compiling and uploading through the terminal (from the main directory) works normally without any errors. 

Console output:

```
[compile] Command: make all -C ~/firmware/main APPDIR=/Users/kamperman/.atom TARGET_DIR=/Users/kamperman/.atom/firmware/photon PLATFORM=photon program-dfu PARTICLE_SERIAL_DEV=/dev/tty.usbmodem20191
particle-offline-compiler.coffee:72 [compile] STDOUT: /Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../modules/photon/user-part all program-dfu

particle-offline-compiler.coffee:72 [compile] STDOUT: /Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../../user 

particle-offline-compiler.coffee:72 [compile] STDOUT: Building file: /Users/kamperman/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.c

particle-offline-compiler.coffee:72 [compile] STDOUT: Invoking: ARM GCC C Compiler

particle-offline-compiler.coffee:72 [compile] STDOUT: mkdir -p ../build/target/user/platform-6-m/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/

particle-offline-compiler.coffee:72 [compile] STDOUT: arm-none-eabi-gcc -DSTM32_DEVICE -DSTM32F2XX -DPLATFORM_THREADING=1 -DPLATFORM_ID=6 -DPLATFORM_NAME=photon -DUSBD_VID_SPARK=0x2B04 -DUSBD_PID_DFU=0xD006 -DUSBD_PID_CDC=0xC006 -DSPARK_PLATFORM -g3 -gdwarf-2 -Os -mcpu=cortex-m3 -mthumb -DINCLUDE_PLATFORM=1 -DPRODUCT_ID=6 -DPRODUCT_FIRMWARE_VERSION=65535 -DMBEDTLS_CONFIG_FILE="<mbedtls_config.h>" -DUSE_STDPERIPH_DRIVER -DDFU_BUILD_ENABLE -DSYSTEM_VERSION_STRING=0.4.9 -DRELEASE_BUILD -I./inc -I../wiring/inc -I../system/inc -I../services/inc -I../communication/lib/mbedtls/include -I../communication/lib/tropicssl/include -I../communication/src -I../hal/inc -I../hal/shared -I../hal/src/photon -I../hal/src/stm32f2xx -I../hal/src/stm32 -I../hal/src/photon/api -I../platform/shared/inc -I../platform/MCU/STM32F2xx/CMSIS/Include -I../platform/MCU/STM32F2xx/CMSIS/Device/ST/Include -I../platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc -I../platform/MCU/shared/STM32/inc -I../platform/MCU/STM32F2xx/STM32_StdPeriph_Driver/inc -I../platform/MCU/STM32F2xx/STM32_USB_Device_Driver/inc -I../platform/MCU/STM32F2xx/STM32_USB_Host_Driver/inc -I../platform/MCU/STM32F2xx/STM32_USB_OTG_Driver/inc -I../dynalib/inc -I/Users/kamperman/.atom/ -I./libraries -I. -MD -MP -MF ../build/target/user/platform-6-m/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.o.d -ffunction-sections -fdata-sections -Wall -Wno-switch -Wno-error=deprecated-declarations -fmessage-length=0 -fno-strict-aliasing -DSPARK=1 -DPARTICLE=1 -DSTART_DFU_FLASHER_SERIAL_SPEED=14400 -DSTART_YMODEM_FLASHER_SERIAL_SPEED=28800 -DSPARK_PLATFORM_NET=BCM9WCDUSI09 -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc  -DUSER_FIRMWARE_IMAGE_SIZE=0x20000 -DUSER_FIRMWARE_IMAGE_LOCATION=0x80A0000 -DMODULAR_FIRMWARE=1 -DMODULE_VERSION=3 -DMODULE_FUNCTION=5 -DMODULE_INDEX=1 -DMODULE_DEPENDENCY=4,2,11  -Wno-pointer-sign -std=gnu99 -c -o ../build/target/user/platform-6-m/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.o /Users/kamperman/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.c

particle-offline-compiler.coffee:73 [compile] STDERR: /Users/kamperman/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.c:10:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
                       ^
compilation terminated.

particle-offline-compiler.coffee:73 [compile] STDERR: make[2]: *** [../build/target/user/platform-6-m/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.o] Error 1

particle-offline-compiler.coffee:73 [compile] STDERR: make[1]: *** [user] Error 2

particle-offline-compiler.coffee:73 [compile] STDERR: make: *** [modules/photon/user-part] Error 2

particle-offline-compiler.coffee:74 [compile] Exited with 2
```

**Comment by chuank** [comment]
`tl;dr:` if you can, wipe atom from your system, including your ~/.atom folder and reinstall it without the official Particle Dev packages and try again. the issue is not related to my package. Here's why:

```
[compile] Command: make all -C ~/firmware/main APPDIR=/Users/kamperman/.atom TARGET_DIR=/Users/kamperman/.atom/firmware/photon PLATFORM=photon program-dfu PARTICLE_SERIAL_DEV=/dev/tty.usbmodem20191
particle-offline-compiler.coffee:72 [compile] STDOUT: /Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../modules/photon/user-part all program-dfu
```

Your `APPDIR` shouldn't be pointing to your `~/.atom` folder. [Check the makefile docs for what it should be.](https://github.com/spark/firmware/blob/develop/docs/build.md#variables) I suspect some other package(s) is/are messing up your atom cwd (current working directory) environment variables. 

```
particle-offline-compiler.coffee:73 [compile] STDERR: /Users/kamperman/.atom/packages/particle-dev-cloud-functions/node_modules/spark/node_modules/request/node_modules/node-uuid/benchmark/benchmark-native.c:10:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
                       ^
compilation terminated.
```

Based on your log, the uuid error is caused by the **particle-dev-cloud-functions** package. That's part of the atom-based Particle Dev package.

**Comment by kasperkamperman** [comment]
Ok. I'll close this issue then. I expected working with Atom would be more user friendly, but I don't have time to dive further into it. I build now from the terminal and that works fine. 

Thanks for your help and suggestions anyway.
